# Generated by Django 3.2.8 on 2021-10-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_diarista_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
    ]
